FROM docker.io/alpine:latest
RUN apk add --no-cache grub grub-efi gettext
WORKDIR /EFI/BOOT
RUN echo 'configfile ${cmdpath}/grub.cfg' > /tmp/grub.cfg
RUN grub-mkstandalone -d "/usr/lib/grub/x86_64-efi" -O x86_64-efi --modules="part_gpt part_msdos efi_gop" \
    --locales="en@quot" --themes="" -o "/EFI/BOOT/bootx64.efi" "boot/grub/grub.cfg=/tmp/grub.cfg" -v 2> /grub.log
ARG VMLINUZ
ARG INITRAMFS
ARG KERNEL_PARAMETERS
ARG UUID
ENV VMLINUZ="${VMLINUZ}" INITRAMFS="${INITRAMFS}" KERNEL_PARAMETERS="${KERNEL_PARAMETERS}" UUID="${UUID}"
COPY grub.cfg /
RUN envsubst < /grub.cfg > grub.cfg
CMD ["cp", "--recursive", "--verbose", "/EFI", "/output/"]